services:
  traefik:
    image: traefik:v3.7
    command:
      # Entrypoint: where Traefik listens for traffic
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Enable the Docker provider so labels on containers become routes
      - "--providers.docker=true"
      # Do NOT expose containers by default — opt-in only
      - "--providers.docker.exposedbydefault=false"
      # Enable the dashboard (insecure = no auth, fine for local learning)
      - "--api.insecure=true"
      # Print access logs so you can see every request
      - "--accesslog=true"
      # Enable the file provider so we can define routes in a config file
      - "--providers.file.directory=/config/dynamic"
      - "--providers.file.watch=true"
    ports:
      - "80:80"       # traffic
      - "8080:8080"   # dashboard
      - "443:443"     # HTTPS traffic
    volumes:
      # Traefik needs to watch the Docker socket to discover containers
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # Traefik needs to read the config file for routes
      - ./certs:/certs:ro
      - ./config:/config:ro
    labels:
      - "traefik.enable=true"
      # Middleware: redirect HTTP to HTTPS
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
      # Middleware: basic auth for the dashboard
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$o49mSww4$$UNHRkKqK8bOIG0HdZnukJ."
      # Remove Security Headers from Responses
      - "traefik.http.middlewares.secure-headers.headers.customResponseHeaders.X-Frame-Options=DENY"
      - "traefik.http.middlewares.secure-headers.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.secure-headers.headers.customResponseHeaders.Referrer-Policy=no-referrer"
      # Rate Limiting Middleware: limit requests to 5 per second with a burst of 10
      - "traefik.http.middlewares.rate-limit.ratelimit.average=5" # average = requests per second sustained
      - "traefik.http.middlewares.rate-limit.ratelimit.burst=10" # burst = how many can spike above that before Traefik starts returning 429

  # Backend A
  alpha:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      # Router rule: requests with Host header = alpha.localhost go here
      - "traefik.http.routers.alpha.rule=Host(`alpha.localhost`)"
      - "traefik.http.routers.alpha.entrypoints=web"
      - "traefik.http.routers.alpha.middlewares=redirect-https"
      # 2nd Router: for HTTPS traffic
      - "traefik.http.routers.alpha-secure.rule=Host(`alpha.localhost`)"
      - "traefik.http.routers.alpha-secure.entrypoints=websecure"
      - "traefik.http.routers.alpha-secure.tls=true"
      # Add all middlewares to the secure router (auth + security headers + rate limiting)
      - "traefik.http.routers.alpha-secure.middlewares=rate-limit,auth,secure-headers"
      # Service: which backend to send traffic to
      - "traefik.http.routers.alpha-secure.service=alpha"
      # Load Balancer Service: group all the alpha routers together
      - "traefik.http.services.alpha.loadbalancer.server.port=80"



  # Backend B
  beta:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beta.rule=Host(`beta.localhost`)"
      - "traefik.http.routers.beta.entrypoints=web"
      - "traefik.http.routers.beta.middlewares=redirect-https"
