server {
  listen 80;
  server_name _;
  absolute_redirect off;

  location = /about-me {
    return 301 /about-me/;
  }

  location /about-me/ {
    alias /usr/share/nginx/html/;
    index index.html;
  }
}
