server {
  listen 80;
  server_name _;
  absolute_redirect off;

  location = /certifications {
    return 301 /certifications/;
  }

  location /certifications/ {
    alias /usr/share/nginx/html/;
    index index.html;
  }
}
